const transfer_min = 20
const example_rangevalue = "1 - 200"

module.exports = 
{
	"russian":
	{
		"welcome":"Добро пожаловать в *AnyCoin Ripple-XRP Бот* \n*Ваш надёжный кошелёк Ripple-XRP*",
		"currency":"💱Выбрать валюту",
		"buy_xrp":"📈 Купить XRP",
		"sell_xrp":"📉 Продать XRP",
		"sell_xrp_not_allowed":"Продажа доступна от баланса "+transfer_min+" XRP",
		"wallet":"🔑Кошелёк",
		"your_wallet":"Ваш ID Кошелька XRP",
		"use_wallet":"Используйте его чтобы принимать XRP",
		"balance":"Ваш Баланс",
		"change_language":"Сменить язык",
		"transfer_xrp":"Вывести средства",
		"transfer_xrp_not_allowed":"Вывод средств доступен от баланса "+transfer_min+" XRP",
		"market_price":"Рыночная Стоимость",
		"menu_text":"Главное меню",
		"select_currency":"Выберите валюту",
		"sell_xrp_select_bank":"Выберите банк",
		"enter_sum":'Введите минимальное - максимальное значение, пример '+example_rangevalue,
		"invalid_sum":'недопустимое значение, пример '+example_rangevalue,
		"create_offer":"Создать предложение",
		"my_offers":"Мои предложения",
		"no_offers":"Для данного банка предложений не найдено",
		"select_payment":"Выберите или введите способ перевода денег",
		"enter_min_value":"Введите минимальное значение в {currency}",
		"enter_max_value":"Введите максимальное значение в {currency}",
		"enter_description":"Введите описание сделки",
		"enter_name":"Введите название сделки",
		"select_offer_type":"Выберите тип сделки",
		"offer_type_buy":"Купить",
		"offer_type_sell":"Продать",
		"save_offer":"Сохранить предложение?",
		"cancel":"Отмена",
		"restart":"Заново",
		"save":"Сохранить",
		"back":"Назад",
		"invalid_offer_name":"Недопустимое название",
		"enter_price":"Введите цену за 1 XRP в {currency}",
		"no_my_offers":"У вас нет предложений",
		"your_offers":"Ваши предложения",
		"edit_offer":"Редактировать",
		"delete_offer":"Удалить",
		"edit_question":"Вы хотите удалить обьявление - ",
		"sell_orders":"Продажные предложения в системе",
		"buy_orders":"Покупные предложения в системе",
		"no_operations":"Данных предложений в данный момент нет",
		"verification":"Верификация",
		"documents":"Документы",
		"rating":"Рейтинг",
		"reviews":"Отзывы",
		"last_seen":"Был в сети",
		"just_now":"Только что",
		"total1_sell":"Через это объявление можно продать Ripple-XRP по курсу: ",
		"total1_buy":"Через это объявление можно купить Ripple-XRP по курсу: ",
		"total2":"На сумму от - до: ",
		"description":"Описание сделки",
		"mainMenuScene":"Главное меню",
		"buy_offer":"Начать сделку",
		"enter_trade_sum":"Введите сумму сделки от {min} {currency} до {max} {currency}",
		"confirm_trade":"Подтвердите начало сделки",
		"confirm":"Подтверждаю",
		"trade_canceled":"Сделка отменена",
		"trade_confirmed":"Сделка подтверждена",
		"waiting_for_trader":"Ожидаем трейдера, если сделка не будет подтверждена в течении 5 минут она отменится автоматически"
	},
	"english":
	{
		"welcome":"Welcome to *AnyCoin XRP-Ripple Bot*",
		"currency":"💱Select currency",
		"buy_xrp":"📈 Buy XRP",
		"sell_xrp":"📉 Sell XRP",
		"sell_xrp_not_allowed":"Selling is available starting from balance "+transfer_min+" XRP",
		"wallet":"🔑 Wallet",
		"your_wallet":"Your XRP Wallet ID",
		"use_wallet":"Use it to receive XRP",
		"balance":"Your Balance",
		"change_language":"Change language",
		"transfer_xrp":"Transfer Balance",
		"transfer_xrp_not_allowed":"Transfer is available starting from balance "+transfer_min+" XRP",
		"market_price":"Market Price",
		"menu_text":"Main menu",
		"select_currency":"Select a currency",
		"sell_xrp_select_bank":"Select a bank",
		"enter_sum":'Enter a rangevalue, example '+example_rangevalue,
		"invalid_sum":'Invalid rangevalue, example '+example_rangevalue,
		"create_offer":"Create offer",
		"my_offers":"My offers",
		"no_offers":"No offers found for this bank",
		"select_payment":"Select or enter a money transfer method",
		"enter_min_value":"Enter the offer minimum value",
		"enter_max_value":"Enter the offer maximum value",
		"enter_description":"Enter the description of the offer",
		"enter_name":"Enter the name of the offer",
		"select_offer_type":"Select an offer type",
		"offer_type_buy":"Buy",
		"offer_type_sell":"Sell",
		"save_offer":"Save this offer?",
		"cancel":"Cancel",
		"restart":"Reset",
		"save":"Save",
		"back":"Back",
		"invalid_offer_name":"Invalid name",
		"enter_price":"Enter your price for 1 Ripple-XRP",
		"no_my_offers":"You have no offers",
		"your_offers":"Your offers",
		"edit_offer":"Edit offer",
		"delete_offer":"Delete",
		"edit_question":"Would you like to delete your offer - ",
		"sell_orders":"Sell offers in the system ",
		"buy_orders":"Buy offers in the system ",
		"no_operations":"No offers of this type available",
		"verification":"Verification",
		"documents":"Documents",
		"rating":"Rating",
		"reviews":"Reviews",
		"last_seen":"Last seen:",
		"just_now":"Just now",
		"total1_sell":"Using this offer you can sell XRP: ",
		"total1_buy":"Using this offer you can buy XRP: ",
		"total2":"for the amount min - max: ",
		"description":"Offer description",
		"mainMenuScene":"Main menu",
		"buy_offer":"Start Trade",
		"enter_trade_sum":"Enter a trade amount starting from {min} {currency} to the maximum of {max} {currency}",
		"confirm_trade":"Confirm start of trade",
		"confirm":"Confirm",
		"trade_canceled":"Сделка отменена",
		"trade_confirmed":"Сделка подтверждена",
		"waiting_for_trader":"Waiting for remote trader, if the trade shall not be confirmed in 5 minutes it will be canceled"
	}
}