const transfer_min = 20
const example_rangevalue = "1 - 200"

module.exports = 
{
	"russian":
	{
		"welcome":"Добро пожаловать в *AnyCoin XRP-Ripple Бот*",
		"currency":"💱Выбрать валюту",
		"buy_xrp":"📈 Купить XRP",
		"sell_xrp":"📉 Продать XRP",
		"sell_xrp_not_allowed":"Продажа доступна от баланса "+transfer_min+" XRP",
		"wallet":"🔑 Кошелёк",
		"your_wallet":"Ваш ID Кошелька XRP",
		"use_wallet":"Используйте его чтобы принимать XRP",
		"balance":"Ваш Баланс",
		"change_language":"Сменить язык",
		"transfer_xrp":"Вывести средства",
		"transfer_xrp_not_allowed":"Вывод средств доступен от баланса "+transfer_min+" XRP",
		"market_price":"Рыночная Стоимость",
		"menu_text":"Главное меню",
		"select_currency":"Выберите валюту",
		"sell_xrp_select_bank":"Выберите банк",
		"enter_sum":'Введите минимальное - максимальное значение, пример '+example_rangevalue,
		"invalid_sum":'недопустимое значение, пример '+example_rangevalue,
		"create_offer":"Создать предложение",
		"my_offers":"Мои предложения",
		"no_offers":"Предложений не найдено для данного банка",
		"select_payment":"Выберите или введите способ перевода денег",
		"enter_min_value":"Введите минимальное значение",
		"enter_max_value":"Введите максимальное значение",
		"enter_description":"Введите описание сделки",
		"enter_name":"Введите название сделки",
		"select_offer_type":"Выберите тип сделки",
		"offer_type_buy":"Купить",
		"offer_type_sell":"Продать",
		"save_offer":"Сохранить предложение?",
		"cancel":"Отмена",
		"restart":"Заново",
		"save":"Сохранить",
		"back":"Назад",
		"invalid_offer_name":"Недопустимое название",
		"enter_price":"Введите цену за 1 XRP",
		"no_my_offers":"У вас нет предложений",
		"your_offers":"Ваши предложения",
		"edit_offer":"Редактировать",
		"delete_offer":"Удалить",
		"edit_question":"Вы хотите удалить обьявление - "
	},
	"english":
	{
		"welcome":"Welcome to *AnyCoin XRP-Ripple Bot*",
		"currency":"💱Select currency",
		"buy_xrp":"📈 Buy XRP",
		"sell_xrp":"📉 Sell XRP",
		"sell_xrp_not_allowed":"Selling is available starting from balance "+transfer_min+" XRP",
		"wallet":"🔑 Wallet",
		"your_wallet":"Your XRP Wallet ID",
		"use_wallet":"Use it to receive XRP",
		"balance":"Your Balance",
		"change_language":"Change language",
		"transfer_xrp":"Transfer Balance",
		"transfer_xrp_not_allowed":"Transfer is available starting from balance "+transfer_min+" XRP",
		"market_price":"Market Price",
		"menu_text":"Main menu",
		"select_currency":"Select a currency",
		"sell_xrp_select_bank":"Select a bank",
		"enter_sum":'Enter a rangevalue, example '+example_rangevalue,
		"invalid_sum":'Invalid rangevalue, example '+example_rangevalue,
		"create_offer":"Create offer",
		"my_offers":"My offers",
		"no_offers":"No offers found for this bank",
		"select_payment":"Select or enter a money transfer method",
		"enter_min_value":"Введите минимальное значение",
		"enter_max_value":"Введите максимальное значение",
		"enter_description":"Введите описание сделки",
		"enter_name":"Введите название сделки",
		"select_offer_type":"Выберите тип сделки",
		"offer_type_buy":"Купить",
		"offer_type_sell":"Продать",
		"save_offer":"Сохранить предложение?",
		"cancel":"Отмена",
		"restart":"Заново",
		"save":"Сохранить",
		"back":"Назад",
		"invalid_offer_name":"Недопустимое название",
		"enter_price":"Введите цену за 1 XRP",
		"no_my_offers":"У вас нет предложений",
		"your_offers":"Ваши предложения",
		"edit_offer":"Редактировать",
		"delete_offer":"Удалить",
		"edit_question":"Вы хотите редактировать или удалить обьявление - "
	}
}